// DATA ACTIONS CONSTANTS
export const SET_CURRENT_USER_SUCCESS = "SET_CURRENT_USER";
export const LOCATION_CHANGE = "LOCATION_CHANGE";
export const GET_CLASSES_BEGIN = "GET_CLASSES_BEGIN";
export const GET_CLASSES_SUCCESS = "GET_CLASSES_SUCCESS";
export const GET_CLASSES_FAILURE = "GET_CLASSES_FAILURE";

export const GET_STUDENTS_BEGIN = "GET_STUDENTS_BEGIN";
export const GET_STUDENTS_SUCCESS = "GET_STUDENTS_SUCCESS";
export const GET_STUDENTS_FAILURE = "GET_STUDENTS_FAILURE";

export const GET_EVENTS_BEGIN = "GET_EVENTS_BEGIN";
export const GET_EVENTS_SUCCESS = "GET_EVENTS_SUCCESS";
export const GET_EVENTS_FAILURE = "GET_EVENTS_FAILURE";

export const UPDATE_EVENT_BEGIN = "UPDATE_EVENT_BEGIN";
export const UPDATE_EVENT_SUCCESS = "UPDATE_EVENT_SUCCESS";
export const UPDATE_EVENT_FAILURE = "UPDATE_EVENT_FAILURE";

export const STUDENT_CHECK_TOOGLE_BEGIN = "STUDENT_CHECK_TOOGLE_BEGIN";
export const STUDENT_CHECK_TOOGLE_SUCCESS = "STUDENT_CHECK_TOOGLE_SUCCESS";
export const STUDENT_CHECK_TOOGLE_FAILURE = "STUDENT_CHECK_TOOGLE_FAILURE";

// UI ACTIONS CONSTANTS
export const CHANGE_PAGE = "CHANGE_PAGE";
export const SET_HEADER_TITLE = "SET_HEADER_TITLE";
