// DATA ACTIONS CONSTANTS
export const SET_CURRENT_USER_SUCCESS = 'SET_CURRENT_USER';

export const GET_CLASSES_BEGIN = 'GET_CLASSES_BEGIN';
export const GET_CLASSES_SUCCESS = 'GET_CLASSES_SUCCESS';
export const GET_CLASSES_FAILURE = 'GET_CLASSES_FAILURE';

export const GET_STUDENTS_BEGIN = 'GET_STUDENTS_BEGIN';
export const GET_STUDENTS_SUCCESS = 'GET_STUDENTS_SUCCESS';
export const GET_STUDENTS_FAILURE = 'GET_STUDENTS_FAILURE';

// UI ACTIONS CONSTANTS
export const CHANGE_PAGE = 'CHANGE_PAGE';
export const SET_HEADER_TITLE = 'SET_HEADER_TITLE';
